version: 1.0.{build}
image: Visual Studio 2017

environment:
  CI: "true"
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - docker version

test_script:
  - node --version
  - npm --version
  - npm run test-ci

build: off
  
